### ISSUE TITLE
PHP7.2 Image Magick Issue

### ISSUE THREAD

**Issue by dpfaffenbauer** [dpfaffenbauer/pimcore-docker#7]
```
[2018-07-25 15:36:29] pimcore.ERROR: Unable to load image: /var/www/html/web/var/assets/design/Logo_300x66.jpg [] []
[2018-07-25 15:36:29] pimcore.ERROR: ImagickException: unable to open image ':/var/www/html/web/var/assets/design/Logo_300x66.jpg': No such file or directory @ error/blob.c/OpenBlob/3469 in /var/www/html/pimcore/lib/Pimcore/Image/Adapter/Imagick.php:110 Stack trace: #0 /var/www/html/pimcore/lib/Pimcore/Image/Adapter/Imagick.php(110): Imagick->readimage(':/var/www/html/...') #1 /var/www/html/pimcore/models/Asset/Image/Thumbnail/Processor.php(193): Pimcore\Image\Adapter\Imagick->load('/var/www/html/w...') #2 /var/www/html/pimcore/models/Asset/Image/Thumbnail.php(138): Pimcore\Model\Asset\Image\Thumbnail\Processor::process(Object(Pimcore\Model\Asset\Image), Object(Pimcore\Model\Asset\Image\Thumbnail\Config), '/var/www/html/w...', false, true, false) #3 /var/www/html/pimcore/models/Asset/Image/Thumbnail.php(114): Pimcore\Model\Asset\Image\Thumbnail->generate(false) #4 /var/www/html/pimcore/models/Asset/Image.php(137): Pimcore\Model\Asset\Image\Thumbnail->getFileSystemPath() #5 /var/www/html/pimcore/models/Asset/Image.php(81): Pimcore\Model\Asset\Image->generateLowQualityPreview() #6 /var/www/html/pimcore/models/Asset.php(504): Pimcore\Model\Asset\Image->update(Array) #7 /var/www/html/pimcore/models/Asset.php(358): Pimcore\Model\Asset->save() #8 /var/www/html/pimcore/lib/Pimcore/Bundle/AdminBundle/Controller/Admin/AssetController.php(338): Pimcore\Model\Asset::create('71', Array) #9 /var/www/html/pimcore/lib/Pimcore/Bundle/AdminBundle/Controller/Admin/AssetController.php(224): Pimcore\Bundle\AdminBundle\Controller\Admin\AssetController->addAsset(Object(Symfony\Component\HttpFoundation\Request)) #10 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(151): Pimcore\Bundle\AdminBundle\Controller\Admin\AssetController->addAssetAction(Object(Symfony\Component\HttpFoundation\Request)) #11 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #12 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(202): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #13 /var/www/html/web/app.php(55): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request)) #14 {main} [] []
```

**Comment by dpfaffenbauer** [comment]
should be solve now
